### ISSUE TITLE
Pick and Place object with stable end-effector

### ISSUE THREAD

**Issue by afr2903** [RoBorregos/home-manipulation#1]
For the task of `Serve breakfast`, the robot has to grab an object, and rotate it to serve its contents (food of liquid). The main problem is that our current `pick and place` pipeline isn't built to maintain the end-effector in a stable as its movement is not limited to cartesian translations.

**Comment by afr2903** [comment]
One part of the task is to upload the current developments with runs in the terminal.

The second part is the programming of the nodes.

**Comment by EmilianoHFlores** [comment]
Pick and Place tasks with stable end effector can now be performed with stability. The issue will not be closed until refactorization is done in both the cartesian_movement package and the main manipulation server.

**Comment by EmilianoHFlores** [comment]
Issue will be closed and fixes for this branch will be separated in their respective issues.
